export const tourData = [
  {
    id: 1,
    city: "bucuresti",
    img: "./img/bucuresti.jpg",
    name: "bucuresti casa poporului tour",
    info:
      "The Palace of the Parliament (Romanian: Casa poporului) is the seat of the Parliament of Romania, located atop Dealul Spirii in Bucharest, the national capital. The Palace has a height of 84 metres (276 ft), a floor area of 365,000 square metres (3,930,000 sq ft) and a volume of 2,550,000 cubic metres (90,000,000 cu ft). The Palace of the Parliament is the heaviest building in the world, weighing about 4,098,500,000 kilograms (9.04 billion pounds; 4.10 million tonnes). The building was designed and supervised by chief architect Anca Petrescu, with a team of approximately 700 architects, and constructed over a period of 13 years (1984–97) in Socialist realist and modernist Neoclassical architectural forms and styles, with socialist realism in mind. The Palace was ordered by Nicolae Ceaușescu (1918–1989), the president of Communist Romania and the second of two longtime heads of state in power in the country since World War II, during a period in which the personality cult of political worship and adoration was noticeably increased for him and his family. Known for its ornate interior composed of 23 sections, it houses the two houses of the Parliament of Romania: the Senate (Senat) and the Chamber of Deputies (Camera Deputaților), along with three museums and an international conference center. The several museums hosted inside the Palace are the National Museum of Contemporary Art, the Museum of Communist Totalitarianism (established in 2015) and the Museum of the Palace. Though originally named the House of the Republic when under its long period of construction (Romanian: Casa Republicii), after the Romanian Revolution in December 1989 it became widely known as The People's House (Romanian: Casa Poporului). Due to its impressive endowments, events organized by state institutions and international bodies such as conferences, symposia, and others take place there, but even so about 70% of the building still remains empty. As of 2008, the Palace of the Parliament is valued at €3 billion ($3.4 billion), making it also the most expensive administrative building in the world. The cost of heating and electric use and lighting alone exceeds $6 million per year, comparable to the total cost for powering a medium-sized city."
  },
  {
    id: 2,
    city: "hunedoara",
    img: "./img/hunedoara.jpg",
    name: "hunedoara castelul corvinilor tour",
    info:
      "Corvin Castle was laid out in 1446, when construction began on the orders of Voivode of Transylvania John Hunyadi (Hungarian: Hunyadi János, Romanian: Iancu or Ioan de Hunedoara) who wanted to transform the former keep built by Charles I of Hungary. The castle was originally given to John Hunyadi's father, Voyk (Vajk), by Sigismund of Luxembourg, king of Hungary and Croatia, as severance in 1409. It was also in 1446 that John Hunyadi was elected as the regent-governor by the Diet. Built in a Renaissance-Gothic style and constructed over the site of an older fortification on a rock above the smaller Zlaști River, the castle is a large and imposing structure with tall towers, bastions, an inner courtyard, diversely coloured roofs, and myriads of windows and balconies adorned with stone carvings. The castle also features a double wall for enhanced fortification and is flanked by both rectangular and circular towers, an architectural innovation for the period's Transylvanian architecture. Some of the towers (the Capistrano Tower, the Deserted Tower and the Drummers' Tower) were used as prisons. The Buzdugan Tower (a type of mace after which it was named) was solely built for defensive purposes and it had its exterior decorated with geometric motifs. The rectangular shaped towers have large openings to accommodate larger weapons. The castle has three large areas: the Knight's Hall, the Diet Hall and the circular stairway. The halls are rectangular in shape and are decorated with marble. The Diet Hall was used for ceremonies or formal receptions whilst the Knight's Hall was used for feasts. In 1456, John Hunyadi died and work on the castle stagnated. Starting with 1458, new commissions were being undergone to construct the Matia Wing of the castle. In 1480, work was completely stopped on the castle and it was recognised as being one of the biggest and most impressive buildings in Eastern Europe. The 16th century did not bring any improvements to the castle, but during the 17th century new additions were made, for aesthetic and military purposes. Aesthetically, the new Large Palace was built facing the town. A two level building, it hosted living chamber and a large living area. For military purposes, two new towers were constructed: the White Tower and the Artillery Tower. Also, the external yard was added, used for administration and storage. The current castle is the result of a fanciful restoration campaign undertaken after a disastrous fire and many decades of total neglect. It has been noted that modern architects projected to it their own wistful interpretations of how a great Gothic castle should look."
  },
  {
    id: 3,
    city: "sibiu",
    img: "./img/sibiu.jpg",
    name: "sibiu castelul de lut tour",
    info:
      "The hotel’s owners, Razvan and Gabriela Vasile, sold their home in Romania’s capital city of Bucharest in order to bring this clay fairytale castle into reality. The Valley of the Fairies, situated near the tiny village of Porumbacu De Sus, is 24 miles from the city of Sibiu. Its remote location and jaw-dropping views add to the hotel’s charm and mystique, effortlessly giving visitors the sense that they have traveled not only distance, but also time, in order to arrive at their destination. Aside from its charming design and scenic surrounding landscape, perhaps the most interesting feature of the eco-friendly hotel is how it was built. Eschewing all modern building techniques, the hotel is composed primarily of clay and sand. The 10-room chalet was designed by eco architect Ileana Mavrodin, along with the Vasiles, and built by area craftsmen. “The exterior plastering is of lime and sand and the towers are of river stone, built with lime and sand,” said Razvan Vasile. “Everything is made with natural materials, and the windows and doors are different, each room having its own separate entrance.”"
  },
  {
    id: 4,
    city: "timisoara",
    img: "./img/timisoara.jpg",
    name: "timisoara city tour",
    info:
      "Nicknamed the Little Vienna or the City of Flowers, Timișoara is considered the informal capital city of the historical Banat. The country's third most populous city is the economic hub of the region, with 319,279 inhabitants as of the 2011 census. It is home to almost a half-million inhabitants in the metropolitan area, as well as ~50,000 students from over 50 countries. Today, Timișoara, like many other large cities in Romania, is a medical tourism service provider especially for dental care. It also offers excellent academic institutions, attracting thousands of international students annually, mainly at its medical school. As a technology hub, the city has one of the most powerful IT sectors in Romania alongside Bucharest, Cluj-Napoca, Iași, and Brașov, becoming a popular tech destination according to Financial Times. In 2013 Timișoara had the fastest internet download speed in the world. Along with Oradea, Timișoara is part of the Art Nouveau European Route. It was the first city in the Habsburg Monarchy with street lighting (1760) and the first European city to be lit by electric street lamps in 1884. It opened the first public lending library with a reading room in the Habsburg Empire and built a municipal hospital 24 years before Vienna. Also, it published the first German newspaper in Southeast Europe (Temeswarer Nachrichten). It has been an important centre for music in Europe since the 19th century. The Romanian Revolution began in Timișoara. The city will be the next European Capital of Culture in 2023."
  }
];
